---
kind: pipeline
type: exec
name: default
platform:
  os: linux
  arch: amd64
clone:
  disable: true
steps:
- name: clone
  commands:
  - pwd
  - git clone ssh://git@iohub.dev/lxsang/antd-web-apps.git
  - cd ./antd-web-apps && git checkout master
- name: build
  commands:
  - cd ./antd-web-apps
  - BUILDDIR=/opt/www/htdocs make
trigger:
  branch:
  - master
